theme: jekyll-theme-dinky
title: Welcome to Jenna Taylor's homepage!
description: This website is where I will share my work and the current projects that I am working on. Be sure to keep an eye out for upcoming projects!
